version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: google-libphonenumber
    versions:
    - 3.2.16
    - 3.2.17
    - 3.2.18
  - dependency-name: joi
    versions:
    - 17.3.0
    - 17.4.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: jest-cli
    versions:
    - 26.6.3
  - dependency-name: jest
    versions:
    - 26.6.3
